GET http://localhost:5085/stocks

###
GET http://localhost:5085/stocks/1

###
POST http://localhost:5085/stocks
Content-Type: application/json

{
    "stockSymbol": "MSFC",
    "userid": 1
}

###
PUT http://localhost:5085/stocks/1
Content-Type: application/json

{
    "stockName": "GOOG",
    "userid": 1
}